[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Full"

opacity = 0.9
blur = true

option_as_alt = "Both"

[font]
normal=  {family = "OpenDyslexicM Nerd Font Mono", style = "Regular"}
offset.y=2
size = 16

[keyboard]
bindings = [
  ##  {key = "V", mods = "Control", action = "Paste"}
]

[colors.primary]

background = "#1a212e"
foreground = "#93a4c3"
bright_foreground = "#ffffff"

[colors.cursor]

text = "#282a36"
cursor = "#f8f8f2"

[colors.vi_mode_cursor]

text = "CellBackground"
cursor = "CellForeground"

[colors.selection]

text = "CellForeground"
background = "#44475a"

[colors.normal]

black = "#0c0e15"
red = "#f65866"
green = "#8bcd5b"
yellow = "#efbd5d"
blue = "#41a7fc"
magenta = "#c75ae8"
cyan = "#34bfd0"
white = "#93a4c3"

[colors.bright]

black = "#6272a4"
red = "#ff6e6e"
green = "#69ff94"
yellow = "#ffffa5"
blue = "#d6acff"
magenta = "#ff92df"
cyan = "#a4ffff"
white = "#ffffff"

[colors.search.matches]

foreground = "#44475a"
background = "#50fa7b"

[colors.search.focused_match]

foreground = "#44475a"
background = "#ffb86c"

[colors.footer_bar]

background = "#282a36"
foreground = "#f8f8f2"

[colors.hints.start]

foreground = "#282a36"
background = "#f1fa8c"

[colors.hints.end]

foreground = "#f1fa8c"
background = "#282a36"
